name: CI main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Tag new version
      run: |
        cd ios
        fastlane new_build_number
        fastlane push_build_changes

    - name: Run yarn
      run: yarn
    
    #iOS setup
    - name: Run pod
      run: |
        cd ios
        pod install 

    - name: Build file ipa iOS
      run: |
        cd ios
        fastlane ios enterprise_lane

    #android setup
    - name: Set env
      run: |
        echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

    - name: Run jetifier
      run: yarn run jetify

    - name: Build file apk Android
      run: |
        cd android
        fastlane android enterprise
      env:
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8