name: CI main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Tag new version
      run: |
        cd ios
        fastlane new_build_number
        fastlane push_version_changes

    #android setup
    - name: Set env
      run: |
        echo "LC_ALL=en_US.UTF-8" >> $GITHUB_ENV
        echo "LANG=en_US.UTF-8" >> $GITHUB_ENV

    - name: Run jetifier
      run: |
        yarn
        yarn run jetify

    - name: Build file apk 
      run: |
        cd android
        fastlane android enterprise
      env:
        LANG: en_US.UTF-8
        LC_ALL: en_US.UTF-8